env:
  global:
    - CC_TEST_REPORTER_ID=747206278eec620edf89a18fb4d4ecdcbe5393ce34ebcbb0fe100244436097bf
    - GO111MODULE=on

language: go
go:
- "1.11.x"

before_install:
  - go get golang.org/x/tools/cmd/cover


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -mod=vendor -coverprofile c.out ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
    slack: codebazaar:dfUey8QKvSJBHhdpNaFBSjMH
